"use server";

import crypto from "crypto";
import { existsSync, readFileSync, writeFileSync } from "fs";
import path from "path";

/**
 * Generate a new NEXTAUTH_SECRET, write it to .env.local, and return it.
 * Safe to call only during first-run setup — before any user sessions exist.
 */
export async function regenerateSecret(): Promise<{ secret: string }> {
  const secret = crypto.randomBytes(32).toString("base64");

  const ENV_LOCAL = path.join(process.cwd(), ".env.local");
  const map = new Map<string, string>();

  if (existsSync(ENV_LOCAL)) {
    for (const line of readFileSync(ENV_LOCAL, "utf-8").split("\n")) {
      if (!line || line.startsWith("#") || !line.includes("=")) continue;
      const [k, ...rest] = line.split("=");
      map.set(k.trim(), rest.join("=").trim());
    }
  }

  map.set("NEXTAUTH_SECRET", secret);
  process.env.NEXTAUTH_SECRET = secret;

  const lines = ["# Auto-generated by Pugmill — do not commit", ""];
  for (const [k, v] of map) lines.push(`${k}=${v}`);
  writeFileSync(ENV_LOCAL, lines.join("\n") + "\n");

  return { secret };
}
