/* ============================================================
 * REPLIT AGENT — PREREQUISITE CHECKLIST
 * Read and complete these steps BEFORE installing dependencies
 * or starting the application. Do not skip.
 * ============================================================
 *
 * STEP 1 — Ask the user for their production URL
 *   Say to the user:
 *   "Before I start the setup, I need your production URL.
 *    Open Replit's deployment panel or domain settings and
 *    paste the URL here (e.g. https://yourapp.replit.app)."
 *   Wait for their reply before continuing.
 *
 * STEP 2 — Save it using the Replit secrets skill (NOT as plain text)
 *   Use the same environment-secrets skill used for NEXTAUTH_SECRET.
 *   This presents the user with a confirmation dialog they must interact
 *   with — do not just mention the value in chat, that will be ignored.
 *   Name:  PRODUCTION_URL
 *   Value: (the URL the user gave you)
 *
 * STEP 3 — Then proceed with the rest of the setup
 *
 * WHY THIS MATTERS:
 * This script writes NEXTAUTH_URL from PRODUCTION_URL when the
 * production container first boots. If PRODUCTION_URL is missing,
 * NEXTAUTH_URL will be wrong and login will fail in production.
 * ============================================================
 */

/**
 * replit-init.ts
 *
 * First-run setup wizard for Replit deployments. Idempotent — safe to run
 * on every `npm run dev` or `npm run start`.
 *
 * What it does:
 *   1. Checks DATABASE_URL is available (provided by Replit's PostgreSQL module)
 *   2. Auto-generates NEXTAUTH_SECRET  (writes to .env.local)
 *   3. Dev:  auto-detects NEXTAUTH_URL from REPLIT_DEV_DOMAIN or REPL_SLUG/REPL_OWNER
 *      Prod: auto-detects NEXTAUTH_URL from REPL_SLUG/REPL_OWNER; PRODUCTION_URL secret overrides (custom domains only)
 *   4. Creates all database tables     (IF NOT EXISTS — never drops)
 *   5. Dev / fresh prod: runs migrations
 *      Existing prod install: skips migrations (run `npm run db:migrate` manually)
 *   6. Verifies public/uploads/ is writable (image upload smoke-test)
 *   7. Prints a prompt to visit /setup to create the admin account
 *   8. Dev only: writes .replit-setup-complete (sentinel — skips this script on future restarts)
 *
 * On non-Replit environments: exits immediately (no-op).
 * Run manually: npm run replit:init  (bypasses the sentinel)
 *
 * To force a re-run after initial setup: delete .replit-setup-complete, then
 * run `npm run replit:init`.
 *
 * NOTE FOR AI AGENTS: Read AGENT.md at the project root before making changes.
 * It contains architectural rules that apply to all automated work on this repo.
 */

import crypto from "crypto";
import { existsSync, readFileSync, writeFileSync } from "fs";
import path from "path";

// ─── Detect environment ───────────────────────────────────────────────────────
const isReplit = !!(
  process.env.REPL_SLUG ||
  process.env.REPLIT_DEV_DOMAIN ||
  process.env.REPLIT_CLUSTER
);

if (!isReplit) {
  process.exit(0);
}

/** True when running inside a Replit deployment (production container). */
const isProd = process.env.REPLIT_DEPLOYMENT === "1";

// ─── Sentinel: skip on subsequent dev restarts (not used in prod containers) ──
const ROOT = process.cwd();
const SENTINEL = path.join(ROOT, ".replit-setup-complete");
const isForced = process.env.REPLIT_REINIT === "1";

if (!isProd && !isForced && existsSync(SENTINEL)) {
  // Already set up in dev — fast exit so `npm run dev` restarts stay snappy
  process.exit(0);
}

// ─── .env.local helpers ───────────────────────────────────────────────────────
const ENV_LOCAL = path.join(ROOT, ".env.local");

function readEnvLocal(): Map<string, string> {
  const map = new Map<string, string>();
  if (!existsSync(ENV_LOCAL)) return map;
  for (const line of readFileSync(ENV_LOCAL, "utf-8").split("\n")) {
    if (!line || line.startsWith("#") || !line.includes("=")) continue;
    const [k, ...rest] = line.split("=");
    map.set(k.trim(), rest.join("=").trim());
  }
  return map;
}

function writeEnvLocal(map: Map<string, string>) {
  const lines = ["# Auto-generated by replit-init — do not commit", ""];
  for (const [k, v] of map) lines.push(`${k}=${v}`);
  writeFileSync(ENV_LOCAL, lines.join("\n") + "\n");
}

/** Returns value from process.env (Replit secrets) or .env.local, in that order. */
function getVar(key: string, envMap: Map<string, string>): string | undefined {
  return process.env[key] || envMap.get(key);
}

/**
 * DB-backed check for an existing install.
 * Returns true if admin_users table exists AND has at least one row.
 * Returns false if the table is missing (fresh install) or empty.
 */
async function checkExistingInstall(): Promise<boolean> {
  try {
    const { db } = await import("../src/lib/db");
    const { adminUsers } = await import("../src/lib/db/schema");
    const rows = await db.select().from(adminUsers).limit(1);
    return rows.length > 0;
  } catch {
    // Table doesn't exist yet — this is a fresh install
    return false;
  }
}

// ─── Main ─────────────────────────────────────────────────────────────────────
async function main() {
  console.log(`\nPugmill CMS — ${isProd ? "Production" : "First Run"} Setup\n`);

  // ── Step 1: DATABASE_URL ────────────────────────────────────────────────────
  if (!process.env.DATABASE_URL) {
    console.error(
      "  Error: DATABASE_URL is not set.\n" +
      "  On Replit, add the PostgreSQL module from the Tools sidebar — it sets\n" +
      "  DATABASE_URL automatically. Then run: npm run replit:init\n"
    );
    process.exit(1);
  }

  // ── Step 2: NEXTAUTH_SECRET, AI_ENCRYPTION_KEY, and NEXTAUTH_URL ───────────
  const envMap = readEnvLocal();
  const configured: string[] = [];

  if (!getVar("NEXTAUTH_SECRET", envMap)) {
    const secret = crypto.randomBytes(32).toString("base64");
    envMap.set("NEXTAUTH_SECRET", secret);
    process.env.NEXTAUTH_SECRET = secret;
    configured.push("NEXTAUTH_SECRET");
  }

  if (!getVar("AI_ENCRYPTION_KEY", envMap)) {
    const key = crypto.randomBytes(32).toString("hex");
    envMap.set("AI_ENCRYPTION_KEY", key);
    process.env.AI_ENCRYPTION_KEY = key;
    configured.push("AI_ENCRYPTION_KEY");
  }

  if (isProd) {
    // ── Production: auto-detect URL, with PRODUCTION_URL as a custom-domain override ──
    // We write NEXTAUTH_URL to .env.local so the Next.js server process reads
    // it on startup — setting process.env here alone is not sufficient because
    // prestart runs in a separate process from `next start`.
    //
    // Detection order:
    //   1. PRODUCTION_URL secret — set this for custom domains only
    //   2. REPL_SLUG + REPL_OWNER — standard Replit deployment domain (zero-config)
    const explicitUrl = getVar("PRODUCTION_URL", envMap);
    const autoUrl =
      process.env.REPL_SLUG && process.env.REPL_OWNER
        ? `${process.env.REPL_SLUG}.${process.env.REPL_OWNER}.repl.co`
        : null;
    const rawProductionUrl = explicitUrl || autoUrl;

    if (rawProductionUrl) {
      const url = rawProductionUrl.startsWith("https://")
        ? rawProductionUrl
        : `https://${rawProductionUrl}`;
      process.env.NEXTAUTH_URL = url;
      if (!getVar("NEXTAUTH_URL", envMap)) {
        envMap.set("NEXTAUTH_URL", url);
        configured.push("NEXTAUTH_URL");
      }
      const source = explicitUrl ? "PRODUCTION_URL secret" : "auto-detected";
      console.log(`  Production URL: ${url} (${source})`);

      // Warn loudly when the URL was auto-detected rather than explicitly confirmed —
      // Replit's current UUID-based domain format may not match what auto-detection
      // produces from REPL_SLUG/REPL_OWNER.
      if (!explicitUrl) {
        console.warn(
          "  ┌─────────────────────────────────────────────────────────────────┐\n" +
          "  │ VERIFY: production URL was auto-detected, not explicitly set    │\n" +
          "  │                                                                 │\n" +
          "  │ If the URL above does not match your actual deployment domain,  │\n" +
          "  │ login will not work. To fix:                                    │\n" +
          "  │                                                                 │\n" +
          "  │ Replit → Secrets → New secret:                                  │\n" +
          "  │   Name:  PRODUCTION_URL                                         │\n" +
          "  │   Value: https://your-actual-domain.com                         │\n" +
          "  │                                                                 │\n" +
          "  │ Then redeploy.                                                  │\n" +
          "  └─────────────────────────────────────────────────────────────────┘\n"
        );
      }
    } else {
      console.error(
        "  ┌─────────────────────────────────────────────────────────────────┐\n" +
        "  │ ACTION REQUIRED — login will not work without this             │\n" +
        "  │                                                                 │\n" +
        "  │ Production URL could not be detected. Login redirects and      │\n" +
        "  │ OAuth callbacks will fail until you set it.                    │\n" +
        "  │                                                                 │\n" +
        "  │ Replit → Secrets → New secret:                                  │\n" +
        "  │   Name:  PRODUCTION_URL                                         │\n" +
        "  │   Value: https://your-actual-domain.com                         │\n" +
        "  │                                                                 │\n" +
        "  │ Then redeploy.                                                  │\n" +
        "  └─────────────────────────────────────────────────────────────────┘\n"
      );
    }
  } else {
    // ── Dev: auto-detect NEXTAUTH_URL from Replit dev domain ───────────────
    if (!getVar("NEXTAUTH_URL", envMap)) {
      const domain =
        process.env.REPLIT_DEV_DOMAIN ||
        (process.env.REPL_SLUG && process.env.REPL_OWNER
          ? `${process.env.REPL_SLUG}.${process.env.REPL_OWNER}.repl.co`
          : null);

      if (domain) {
        const url = `https://${domain}`;
        envMap.set("NEXTAUTH_URL", url);
        process.env.NEXTAUTH_URL = url;
        configured.push("NEXTAUTH_URL");
        console.log(`  Dev URL: ${url}`);
      } else {
        console.log(
          "  Warning: Could not detect dev URL.\n" +
          "  Set NEXTAUTH_URL manually in .env.local or as a Replit secret."
        );
      }
    }

    // ── Dev: remind about PRODUCTION_URL only if using a custom domain ────
    if (!getVar("PRODUCTION_URL", envMap)) {
      console.log(
        "  Note: No PRODUCTION_URL secret found.\n" +
        "  Standard Replit deployments will auto-detect the production URL — no action needed.\n" +
        "  Only set PRODUCTION_URL if you are using a custom domain.\n"
      );
    }
  }

  if (configured.length > 0) {
    writeEnvLocal(envMap);
    console.log(`  Auto-configured: ${configured.join(", ")} — saved to .env.local\n`);
  }

  // ── Warn about NEXTAUTH_SECRET persistence in production ─────────────────
  // In dev, .env.local persists on the Replit workspace filesystem — secret is stable.
  // In production, each deployment gets a fresh container and .env.local is gone,
  // so the secret would regenerate on every deploy and invalidate all active sessions.
  // Saving it as a Replit secret pins it permanently across deployments.
  if (!isProd && configured.includes("NEXTAUTH_SECRET")) {
    const secret = envMap.get("NEXTAUTH_SECRET") ?? "";
    console.log(
      "  ┌─────────────────────────────────────────────────────────────────┐\n" +
      "  │ 2 ACTIONS REQUIRED before your first production deployment      │\n" +
      "  │                                                                 │\n" +
      "  │ 1. Save NEXTAUTH_SECRET as a Replit secret so sessions survive  │\n" +
      "  │    container restarts and deployments. Without it, every deploy │\n" +
      "  │    regenerates the secret and signs all users out.              │\n" +
      "  │                                                                 │\n" +
      `  │    Replit → Secrets → New secret:                               │\n` +
      `  │      Name:  NEXTAUTH_SECRET                                     │\n` +
      `  │      Value: ${secret.slice(0, 50).padEnd(50)} │\n` +
      "  │                                                                 │\n" +
      "  │ 2. Save your production URL as a Replit secret so login works   │\n" +
      "  │    after deployment. Ask the user for their production URL now. │\n" +
      "  │    Without it, authentication will fail in production.          │\n" +
      "  │                                                                 │\n" +
      "  │    Replit → Secrets → New secret:                               │\n" +
      "  │      Name:  PRODUCTION_URL                                      │\n" +
      "  │      Value: https://your-production-domain.com                  │\n" +
      "  └─────────────────────────────────────────────────────────────────┘\n"
    );
  }

  // Ensure newly written .env.local values are in process.env for the db import
  const { config: dotenvConfig } = await import("dotenv");
  dotenvConfig({ path: ENV_LOCAL, override: false });

  // ── Step 3: Database schema ─────────────────────────────────────────────────
  if (isProd) {
    // In production, use DB state to decide whether to run migrations.
    // Fresh install (no admin yet): run full setup.
    // Existing install: run createSchema only (IF NOT EXISTS — safe), skip migrations.
    console.log("Database schema");
    const { createSchema } = await import("./create-schema");
    await createSchema();

    const existingInstall = await checkExistingInstall();
    if (!existingInstall) {
      console.log("Fresh install detected — running migrations...");
      const { execSync } = await import("child_process");
      try {
        execSync("tsx scripts/run-migrations.ts", {
          stdio: "inherit",
          env: { ...process.env },
        });
      } catch {
        console.warn("  Warning: one or more migrations reported an error (see above). Continuing...");
      }
    } else {
      console.log(
        "  Existing install detected — skipping automatic migrations.\n" +
        "  To apply pending schema changes, run: npm run db:migrate\n"
      );
    }
  } else {
    // Dev: always run createSchema + migrations (idempotent)
    console.log("Database schema");
    const { createSchema } = await import("./create-schema");
    await createSchema();

    console.log("Running migrations...");
    const { execSync } = await import("child_process");
    try {
      execSync("tsx scripts/run-migrations.ts", {
        stdio: "inherit",
        env: { ...process.env },
      });
    } catch {
      console.warn("  Warning: one or more migrations reported an error (see above). Continuing...");
    }
  }

  // ── Step 4: Verify local upload storage is writable ─────────────────────────
  // A quick write + delete confirms that image uploads will work at runtime.
  // Prints a clear pass/fail the Replit agent (and humans) can see in the log.
  {
    const { mkdirSync, writeFileSync, unlinkSync } = await import("fs");
    const uploadsDir = path.join(ROOT, "public", "uploads");
    const probe = path.join(uploadsDir, ".write-probe");
    try {
      mkdirSync(uploadsDir, { recursive: true });
      writeFileSync(probe, "ok");
      unlinkSync(probe);
      console.log("  ✓ Upload storage: public/uploads/ is writable — image uploads will work.\n");
    } catch (err) {
      console.warn(
        "  ⚠  Upload storage: could not write to public/uploads/.\n" +
        "  Images uploaded through the admin will not be served.\n" +
        "  To fix: ensure the Replit deployment has a persistent volume, or\n" +
        "  switch to S3-compatible storage by setting STORAGE_PROVIDER=s3.\n" +
        `  (${(err as Error).message})\n`
      );
    }
  }

  console.log(
    "  Visit your site URL and go to /setup to create your admin account.\n"
  );

  // ── Step 8 (dev only): write sentinel so future restarts skip this ──────────
  if (!isProd) {
    writeFileSync(SENTINEL, new Date().toISOString() + "\n");
  }

  console.log("Setup complete — starting server...\n");
  process.exit(0);
}

main().catch(err => {
  console.error("\nSetup failed:", err.message ?? err);
  process.exit(1);
});
