/**
 * replit-init.ts
 *
 * First-run setup wizard for Replit deployments. Idempotent — safe to run
 * on every `npm run dev` (it skips steps that are already done).
 *
 * What it does:
 *   1. Auto-generates NEXTAUTH_SECRET  (writes to .env.local)
 *   2. Auto-detects  NEXTAUTH_URL      (from REPLIT_DEV_DOMAIN / REPL_SLUG)
 *   3. Creates all database tables     (IF NOT EXISTS — never drops)
 *   4. Seeds admin user               (skipped if one already exists)
 *   5. Prints credentials clearly
 *
 * On non-Replit environments: exits immediately (no-op).
 * Run manually: npm run replit:init
 */

import crypto from "crypto";
import { existsSync, readFileSync, writeFileSync } from "fs";
import path from "path";

// ─── Detect environment ───────────────────────────────────────────────────────
const isReplit = !!(
  process.env.REPL_SLUG ||
  process.env.REPLIT_DEV_DOMAIN ||
  process.env.REPLIT_CLUSTER
);

if (!isReplit) {
  // Not on Replit — nothing to do here
  process.exit(0);
}

const ROOT = process.cwd();
const ENV_LOCAL = path.join(ROOT, ".env.local");

// ─── .env.local helpers ───────────────────────────────────────────────────────
function readEnvLocal(): Map<string, string> {
  const map = new Map<string, string>();
  if (!existsSync(ENV_LOCAL)) return map;
  for (const line of readFileSync(ENV_LOCAL, "utf-8").split("\n")) {
    if (!line || line.startsWith("#") || !line.includes("=")) continue;
    const [k, ...rest] = line.split("=");
    map.set(k.trim(), rest.join("=").trim());
  }
  return map;
}

function writeEnvLocal(map: Map<string, string>) {
  const lines = ["# Auto-generated by replit-init — do not commit", ""];
  for (const [k, v] of map) lines.push(`${k}=${v}`);
  writeFileSync(ENV_LOCAL, lines.join("\n") + "\n");
}

/** Checks process.env first (Replit secrets), then .env.local */
function getVar(key: string, envMap: Map<string, string>): string | undefined {
  return process.env[key] || envMap.get(key);
}

// ─── Phase 1: Ensure NEXTAUTH_SECRET and NEXTAUTH_URL ────────────────────────
console.log("\nPugmill CMS — Setup\n");

const envMap = readEnvLocal();
const configured: string[] = [];

// NEXTAUTH_SECRET — generate if missing
if (!getVar("NEXTAUTH_SECRET", envMap)) {
  const secret = crypto.randomBytes(32).toString("base64");
  envMap.set("NEXTAUTH_SECRET", secret);
  process.env.NEXTAUTH_SECRET = secret;
  configured.push("NEXTAUTH_SECRET");
}

// NEXTAUTH_URL — detect from Replit env vars
if (!getVar("NEXTAUTH_URL", envMap)) {
  // REPLIT_DEV_DOMAIN is the newer env var (e.g. "myapp.username.repl.co")
  const domain =
    process.env.REPLIT_DEV_DOMAIN ||
    (process.env.REPL_SLUG && process.env.REPL_OWNER
      ? `${process.env.REPL_SLUG}.${process.env.REPL_OWNER}.repl.co`
      : null);

  if (domain) {
    const url = `https://${domain}`;
    envMap.set("NEXTAUTH_URL", url);
    process.env.NEXTAUTH_URL = url;
    configured.push("NEXTAUTH_URL");
    console.log(`  App URL detected: ${url}`);
  } else {
    console.log(
      "  Warning: Could not detect app URL. Set NEXTAUTH_URL manually in .env.local"
    );
  }
}

if (configured.length > 0) {
  writeEnvLocal(envMap);
  console.log(`  Configured: ${configured.join(", ")} → .env.local\n`);
}

// Reload .env.local so db imports pick up the values we just wrote
const { config: dotenvConfig } = await import("dotenv");
dotenvConfig({ path: ENV_LOCAL, override: true });

// ─── Phase 2: Database schema ─────────────────────────────────────────────────
console.log("Database");
const { createSchema } = await import("./create-schema");
await createSchema();

// ─── Phase 3: Admin user ──────────────────────────────────────────────────────
console.log("\nAdmin");

const { db } = await import("../src/lib/db");
const { adminUsers } = await import("../src/lib/db/schema");
const bcrypt = await import("bcryptjs");

const existing = await db.select().from(adminUsers).limit(1);

if (existing.length > 0) {
  console.log("  Admin account already exists — skipping.\n");
} else {
  // Use env vars if provided, otherwise generate sensible defaults
  const email = process.env.ADMIN_EMAIL || "admin@pugmill.local";

  let password: string;
  let passwordSource: string;

  if (process.env.ADMIN_PASSWORD) {
    password = process.env.ADMIN_PASSWORD;
    passwordSource = "from ADMIN_PASSWORD env var";
  } else {
    // Generate a readable random password
    const words = [
      "coral", "amber", "cedar", "flint", "grove",
      "haven", "ivory", "jasper", "maple", "onyx",
    ];
    const w1 = words[crypto.randomInt(words.length)];
    const w2 = words[crypto.randomInt(words.length)];
    const num = crypto.randomInt(1000, 9999);
    password = `${w1}-${w2}-${num}`;
    passwordSource = "auto-generated";
  }

  const name = process.env.ADMIN_NAME || "Admin";
  const passwordHash = await bcrypt.default.hash(password, 12);

  await db.insert(adminUsers).values({
    email,
    name,
    passwordHash,
    role: "admin",
  } as typeof adminUsers.$inferInsert);

  // Seed site config (reads pugmill.config.json or uses built-in defaults)
  const { getConfig } = await import("../src/lib/config");
  await getConfig();

  // Seed default content
  const { seedDefaultContent } = await import("../seeds/default-content");
  const [created] = await db
    .select()
    .from(adminUsers)
    .limit(1);
  await seedDefaultContent(created.id);

  const border = "─".repeat(44);
  console.log(`\n  ┌${border}┐`);
  console.log(`  │  Admin credentials (${passwordSource.padEnd(21)})│`);
  console.log(`  │                                              │`);
  console.log(`  │  Email:    ${email.padEnd(34)}│`);
  console.log(`  │  Password: ${password.padEnd(34)}│`);
  console.log(`  │                                              │`);
  console.log(`  │  Sign in at /admin/login                     │`);
  console.log(`  └${border}┘\n`);

  if (passwordSource === "auto-generated") {
    console.log("  Save these credentials — they won't be shown again.\n");
  }
}

console.log("Setup complete. Starting dev server...\n");
process.exit(0);
