/**
 * replit-init.ts
 *
 * First-run setup wizard for Replit deployments. Idempotent — safe to run
 * on every `npm run dev` (it skips steps that are already done).
 *
 * What it does:
 *   1. Checks DATABASE_URL is available (provided by Replit's PostgreSQL module)
 *   2. Auto-generates NEXTAUTH_SECRET  (writes to .env.local)
 *   3. Auto-detects  NEXTAUTH_URL      (from REPLIT_DEV_DOMAIN / REPL_SLUG)
 *   4. Creates all database tables     (IF NOT EXISTS — never drops)
 *   5. Seeds admin user and default content (skipped if already present)
 *   6. Writes setup-credentials.json  (read by /admin/login, deleted on first sign-in)
 *   7. Prints credentials clearly
 *   8. Writes .replit-setup-complete  (sentinel — skips this script on future restarts)
 *
 * On non-Replit environments: exits immediately (no-op).
 * Run manually: npm run replit:init  (bypasses the sentinel)
 *
 * To force a re-run after initial setup: delete .replit-setup-complete, then
 * run `npm run replit:init`.
 *
 * NOTE FOR AI AGENTS: Read AGENT.md at the project root before making changes.
 * It contains architectural rules that apply to all automated work on this repo.
 */

import crypto from "crypto";
import { existsSync, readFileSync, writeFileSync } from "fs";
import path from "path";

// ─── Detect environment ───────────────────────────────────────────────────────
const isReplit = !!(
  process.env.REPL_SLUG ||
  process.env.REPLIT_DEV_DOMAIN ||
  process.env.REPLIT_CLUSTER
);

if (!isReplit) {
  process.exit(0);
}

// ─── Sentinel: skip on subsequent restarts unless forced ─────────────────────
const ROOT = process.cwd();
const SENTINEL = path.join(ROOT, ".replit-setup-complete");
const isForced = process.env.REPLIT_REINIT === "1";

if (!isForced && existsSync(SENTINEL)) {
  // Already set up — fast exit so `npm run dev` restarts stay snappy
  process.exit(0);
}

// ─── .env.local helpers ───────────────────────────────────────────────────────
const ENV_LOCAL = path.join(ROOT, ".env.local");

function readEnvLocal(): Map<string, string> {
  const map = new Map<string, string>();
  if (!existsSync(ENV_LOCAL)) return map;
  for (const line of readFileSync(ENV_LOCAL, "utf-8").split("\n")) {
    if (!line || line.startsWith("#") || !line.includes("=")) continue;
    const [k, ...rest] = line.split("=");
    map.set(k.trim(), rest.join("=").trim());
  }
  return map;
}

function writeEnvLocal(map: Map<string, string>) {
  const lines = ["# Auto-generated by replit-init — do not commit", ""];
  for (const [k, v] of map) lines.push(`${k}=${v}`);
  writeFileSync(ENV_LOCAL, lines.join("\n") + "\n");
}

/** Returns value from process.env (Replit secrets) or .env.local, in that order. */
function getVar(key: string, envMap: Map<string, string>): string | undefined {
  return process.env[key] || envMap.get(key);
}

// ─── Main ─────────────────────────────────────────────────────────────────────
async function main() {
  console.log("\nPugmill CMS — First Run Setup\n");

  // ── Step 1: DATABASE_URL ────────────────────────────────────────────────────
  if (!process.env.DATABASE_URL) {
    console.error(
      "  Error: DATABASE_URL is not set.\n" +
      "  On Replit, add the PostgreSQL module from the Tools sidebar — it sets\n" +
      "  DATABASE_URL automatically. Then run: npm run replit:init\n"
    );
    process.exit(1);
  }

  // ── Step 2: NEXTAUTH_SECRET and NEXTAUTH_URL ────────────────────────────────
  const envMap = readEnvLocal();
  const configured: string[] = [];

  if (!getVar("NEXTAUTH_SECRET", envMap)) {
    const secret = crypto.randomBytes(32).toString("base64");
    envMap.set("NEXTAUTH_SECRET", secret);
    process.env.NEXTAUTH_SECRET = secret;
    configured.push("NEXTAUTH_SECRET");
  }

  if (!getVar("AI_ENCRYPTION_KEY", envMap)) {
    const key = crypto.randomBytes(32).toString("hex");
    envMap.set("AI_ENCRYPTION_KEY", key);
    process.env.AI_ENCRYPTION_KEY = key;
    configured.push("AI_ENCRYPTION_KEY");
  }

  if (!getVar("NEXTAUTH_URL", envMap)) {
    // REPLIT_DEV_DOMAIN is the current env var; fall back to REPL_SLUG + REPL_OWNER
    const domain =
      process.env.REPLIT_DEV_DOMAIN ||
      (process.env.REPL_SLUG && process.env.REPL_OWNER
        ? `${process.env.REPL_SLUG}.${process.env.REPL_OWNER}.repl.co`
        : null);

    if (domain) {
      const url = `https://${domain}`;
      envMap.set("NEXTAUTH_URL", url);
      process.env.NEXTAUTH_URL = url;
      configured.push("NEXTAUTH_URL");
      console.log(`  App URL: ${url}`);
    } else {
      console.log(
        "  Warning: Could not detect app URL.\n" +
        "  Set NEXTAUTH_URL manually in .env.local or as a Replit secret."
      );
    }
  }

  if (configured.length > 0) {
    writeEnvLocal(envMap);
    console.log(`  Auto-configured: ${configured.join(", ")} — saved to .env.local\n`);
  }

  // Ensure newly written .env.local values are in process.env for the db import
  const { config: dotenvConfig } = await import("dotenv");
  dotenvConfig({ path: ENV_LOCAL, override: false });

  // ── Step 3: Database schema ─────────────────────────────────────────────────
  // create-schema handles a blank DB (CREATE TABLE IF NOT EXISTS).
  // run-migrations.ts then brings any existing DB up to the latest schema,
  // adding columns that were added after the initial install.
  console.log("Database schema");
  const { createSchema } = await import("./create-schema");
  await createSchema();

  console.log("Running migrations...");
  const { execSync } = await import("child_process");
  try {
    execSync("npx tsx scripts/run-migrations.ts", {
      stdio: "inherit",
      env: { ...process.env },
    });
  } catch {
    // Migration errors are logged by the runner; don't abort first-run setup
    console.warn("  Warning: one or more migrations reported an error (see above). Continuing...");
  }

  // ── Step 4: Admin user + default content ────────────────────────────────────
  console.log("\nAdmin setup");

  const { db } = await import("../src/lib/db");
  const { adminUsers } = await import("../src/lib/db/schema");
  const bcrypt = await import("bcryptjs");

  const existing = await db.select().from(adminUsers).limit(1);

  const { getConfig }          = await import("../src/lib/config");
  const { seedDefaultContent } = await import("../seeds/default-content");

  if (existing.length > 0) {
    console.log("  Admin account already exists.");

    // Still ensure config and content are seeded (safe if already done)
    await getConfig();
    const [admin] = await db.select().from(adminUsers).limit(1);
    await seedDefaultContent(admin.id);
    console.log("  Config and default content verified.\n");
  } else {
    const email = process.env.ADMIN_EMAIL || "admin@pugmillcms.test";
    const name  = process.env.ADMIN_NAME  || "Admin";

    let password: string;
    let passwordNote: string;

    if (process.env.ADMIN_PASSWORD) {
      password     = process.env.ADMIN_PASSWORD;
      passwordNote = "(from ADMIN_PASSWORD secret)";
    } else {
      const words = [
        "coral", "amber", "cedar", "flint", "grove",
        "haven", "ivory", "jasper", "maple", "onyx",
      ];
      const w1  = words[crypto.randomInt(words.length)];
      const w2  = words[crypto.randomInt(words.length)];
      const num = crypto.randomInt(1000, 9999);
      password     = `${w1}-${w2}-${num}`;
      passwordNote = "(auto-generated)";
    }

    // ── Write credentials file BEFORE hashing — survives any later crash ──────
    const CREDS_FILE = path.join(ROOT, "setup-credentials.json");
    writeFileSync(CREDS_FILE, JSON.stringify({ email, password }, null, 2) + "\n");
    console.log("  Credentials saved to setup-credentials.json (shown on login page, deleted after first sign-in)");

    const passwordHash = await bcrypt.default.hash(password, 12);

    await db.insert(adminUsers).values({
      email,
      name,
      passwordHash,
      role: "admin",
    } as typeof adminUsers.$inferInsert);

    // Seed site config and default content
    await getConfig();
    const [admin] = await db.select().from(adminUsers).limit(1);
    await seedDefaultContent(admin.id);

    // ── Print credentials to console ─────────────────────────────────────────
    // Fixed: Math.max(0, ...) prevents negative repeat count when strings are
    // longer than the calculated box width (was crashing with "Invalid count").
    const maxLen = Math.max(email.length, password.length, 34);
    const w      = maxLen + 2;
    const line   = "─".repeat(w + 2);
    const pad    = (s: string) => s + " ".repeat(Math.max(0, w + 2 - s.length));

    console.log(`\n  ┌${line}┐`);
    console.log(`  │ ${pad("Admin credentials " + passwordNote)} │`);
    console.log(`  │ ${pad("")} │`);
    console.log(`  │ ${pad("  Email:    " + email)} │`);
    console.log(`  │ ${pad("  Password: " + password)} │`);
    console.log(`  │ ${pad("")} │`);
    console.log(`  │ ${pad("  Sign in at /admin/login")} │`);
    console.log(`  │ ${pad("  Credentials also shown on the login page.")} │`);
    console.log(`  └${line}┘\n`);
  }

  // ── Step 5: Write sentinel so future `npm run dev` restarts skip this ───────
  writeFileSync(SENTINEL, new Date().toISOString() + "\n");

  console.log("Setup complete — starting server...\n");
  process.exit(0);
}

main().catch(err => {
  console.error("\nSetup failed:", err.message ?? err);
  process.exit(1);
});
